BankApp/App.Web/Models/TransferMoney.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace App.Web.Models
{
    public class TransferMoney
    {
        public int ClientFromId { get; set; }
        public int ClientToId { get; set; }
        [Required]
        public decimal Amount { get; set; }

        public TransferMoney()
        {

        }

        public TransferMoney(int clientFromId)
        {
            ClientFromId = clientFromId;                        
        }

        public TransferMoney(int clientFromId, int clientToId)
        {
            ClientFromId = clientFromId;
            ClientToId = clientToId;            
        }
    }
}

BankApp/App.Web/Models/WithdrawMoney.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace App.Web.Models
{
    public class WithdrawMoney
    {
        public int ClientId { get; set; }
        [Required]
        public decimal Amount { get; set; }

        public WithdrawMoney()
        {

        }

        public WithdrawMoney(int clientId)
        {
            ClientId = ClientId;            
        }
    }
}

BankApp/App.Web/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Core;
using App.Web.Models;

namespace App.Web.Controllers
{
    public class BankController : Controller
    {
        private BankService _bankService;
        private ClientService _clientService;

        public BankController(BankService BankService, ClientService ClientService)
        {
            _bankService = BankService;
            _clientService = ClientService;
        }

        // GET: Bank/Transactions
        public ActionResult Transactions(int clientId)
        {
            var transactions = _bankService.GetTransactionsByClientId(clientId).Objs.OrderByDescending(x => x.Created);
            return View(transactions);
        }

        // GET: Bank/DepositMoney
        public ActionResult DepositMoney(int clientId)
        {
            return View(new DepositModel(clientId));
        }

        // POST: Bank/DepositMoney
        [HttpPost]
        public ActionResult DepositMoney(DepositModel model)
        {
            _bankService.DepositMoney(model.ClientId, model.Amount);
            return RedirectToAction("Transactions", "Bank", new { clientId = model.ClientId });
        }

        // GET: Bank/WithdrawMoney
        public ActionResult WithdrawMoney(int clientId)
        {
            return View(new WithdrawMoney(clientId));
        }

        // POST: Bank/WithdrawMoney
        [HttpPost]
        public ActionResult WithdrawMoney(WithdrawMoney model)
        {
            _bankService.WithdrawMoney(model.ClientId, model.Amount);
            return RedirectToAction("Transactions", "Bank", new { clientId = model.ClientId });
        }


        // GET: Bank/TransferMoney
        public ActionResult TransferMoney(int clientId)
        {            
            return View(new TransferMoney(clientId));
        }

        // POST: Bank/TransferMoney
        [HttpPost]
        public ActionResult TransferMoney(TransferMoney model)
        {
            _bankService.TransferMoney(model.ClientFromId, model.ClientToId, model.Amount);
            return RedirectToAction("Transactions", "Bank", new { clientId = model.ClientFromId });
        }

    }
}

BankApp/App.Web/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.Core;

namespace App.Web.Controllers
{
    public class ClientsController : Controller
    {
        private ClientService _clientService;
        private BankService _bankService;

        public ClientsController(ClientService ClientService, BankService BankService)
        {
            _clientService = ClientService;
            _bankService = BankService;
        }

        // GET: Clients
        public ActionResult Index()
        {
            var clients = _clientService.GetAllClients().Objs;
            return View(clients);
        }        
        
        
    }
}

BankApp/App.Web/Views/Bank/DepositMoney.cshtml
@model App.Web.Models.DepositModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepositModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Clients")
</div>

BankApp/App.Web/Views/Bank/Transactions.cshtml
@using App.DataAccess;

<h1>Transactions</h1>

<div>
    @Html.ActionLink("Back to List", "Index", "Clients")
</div>

<table class="table">
    <thead>
        <tr>            
            <th>ID</th>
            <th>Transaction Type</th>
            <th>Amount</th>            
            <th>ClientFrom</th>
            <th>ClientTo</th>
            <th>Created</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var transaction in this.ViewData.Model)
        {
            <tr>
                <td>@transaction.Id</td>                            
                <td>@transaction.TransactionType</td>
                <td>@transaction.Amount</td>
                <td>@(transaction.ClientFrom != null ? transaction.ClientFrom.Name : "")</td>                
                <td>@(@transaction.ClientTo != null ? transaction.ClientTo.Name : "")</td>                
                <td>@(@transaction.Created != null ? transaction.Created : "")</td>                
            </tr>
        }        
    </tbody>    
</table>

BankApp/App.Web/Views/Bank/TransferMoney.cshtml
@using App.DataAccess;
@using App.Core;
@using App.Common;
@using Microsoft.Practices.Unity;
@model App.Web.Models.TransferMoney

@{
    IClientService _clientService = Ioc.Instance.Resolve<IClientService>();

    var clientListItems = _clientService.GetAllClients().Objs
        .Where (x => x.Id != Model.ClientFromId)
        .Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() });    

}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TransferMoney</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">            
            <label class="control-label col-md-2">From</label>            
            <div class="col-md-10">
                @Html.EditorFor( model => model.ClientFromId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientFromId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">To</label>    
            <div class="col-md-10">                
                @Html.DropDownListFor(model => model.ClientToId, clientListItems, "", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClientToId, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Clients")
</div>

BankApp/App.Web/Views/Bank/WithdrawMoney.cshtml
@model App.Web.Models.WithdrawMoney

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DepositModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Clients")
</div>